<?php
/**
 * CampaignRecipient
 *
 * PHP version 7.1.3
 *
 * @category Class
 * @package  ElasticEmail\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Elastic Email REST API
 *
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    To start using this API, you will need your Access Token (available <a href=\"https://elasticemail.com/account#/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    This is the documentation for REST API. If you’d like to read our legacy documentation regarding Web API v2 click <a href=\"https://api.elasticemail.com/public/help\">here</a>.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace ElasticEmail\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the CampaignRecipient model.
 *
 * A set of lists and segments names to read recipients from
 *
 * @package ElasticEmail\Model
 * @author  OpenAPI Generator team
 */
class CampaignRecipient 
{
        /**
     * Names of lists from your Account to read recipients from
     *
     * @var string[]|null
     * @SerializedName("ListNames")
     * @Assert\All({
     *   @Assert\Type("string")
     * })
     * @Type("array<string>")
     */
    protected $listNames;

    /**
     * Names of segments from your Account to read recipients from
     *
     * @var string[]|null
     * @SerializedName("SegmentNames")
     * @Assert\All({
     *   @Assert\Type("string")
     * })
     * @Type("array<string>")
     */
    protected $segmentNames;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->listNames = isset($data['listNames']) ? $data['listNames'] : null;
        $this->segmentNames = isset($data['segmentNames']) ? $data['segmentNames'] : null;
    }

    /**
     * Gets listNames.
     *
     * @return string[]|null
     */
    public function getListNames(): ?array
    {
        return $this->listNames;
    }

    /**
     * Sets listNames.
     *
     * @param string[]|null $listNames  Names of lists from your Account to read recipients from
     *
     * @return $this
     */
    public function setListNames(array $listNames = null)
    {
        $this->listNames = $listNames;

        return $this;
    }

    /**
     * Gets segmentNames.
     *
     * @return string[]|null
     */
    public function getSegmentNames(): ?array
    {
        return $this->segmentNames;
    }

    /**
     * Sets segmentNames.
     *
     * @param string[]|null $segmentNames  Names of segments from your Account to read recipients from
     *
     * @return $this
     */
    public function setSegmentNames(array $segmentNames = null)
    {
        $this->segmentNames = $segmentNames;

        return $this;
    }
}


