<?php
/**
 * CampaignOptions
 *
 * PHP version 7.1.3
 *
 * @category Class
 * @package  ElasticEmail\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Elastic Email REST API
 *
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://elasticemail.com/account#/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    This is the documentation for REST API. If you’d like to read our legacy documentation regarding Web API v2 click <a target=\"_blank\" href=\"https://api.elasticemail.com/public/help\">here</a>.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace ElasticEmail\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the CampaignOptions model.
 *
 * Different send options for a Campaign
 *
 * @package ElasticEmail\Model
 * @author  OpenAPI Generator team
 */
class CampaignOptions 
{
        /**
     * How to order email delivery - by recipients&#39; engagement score or by the time they open the most of the emails that were sent to them
     *
     * @var DeliveryOptimizationType|null
     * @SerializedName("DeliveryOptimization")
     * @Assert\Type("DeliveryOptimizationType")
     * @Type("DeliveryOptimizationType")
     */
    protected $deliveryOptimization;

    /**
     * Should the opens be tracked? If no value has been provided, Account&#39;s default setting will be used.
     *
     * @var bool|null
     * @SerializedName("TrackOpens")
     * @Assert\Type("bool")
     * @Type("bool")
     */
    protected $trackOpens;

    /**
     * Should the clicks be tracked? If no value has been provided, Account&#39;s default setting will be used.
     *
     * @var bool|null
     * @SerializedName("TrackClicks")
     * @Assert\Type("bool")
     * @Type("bool")
     */
    protected $trackClicks;

    /**
     * Date when this Campaign is scheduled to be sent on
     *
     * @var \DateTime|null
     * @SerializedName("ScheduleFor")
     * @Assert\DateTime()
     * @Type("DateTime")
     */
    protected $scheduleFor;

    /**
     * Optional options for A/X split campaigns. Will be ignored if only one template content was provided
     *
     * @var SplitOptions|null
     * @SerializedName("SplitOptions")
     * @Assert\Type("SplitOptions")
     * @Type("SplitOptions")
     */
    protected $splitOptions;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->deliveryOptimization = isset($data['deliveryOptimization']) ? $data['deliveryOptimization'] : null;
        $this->trackOpens = isset($data['trackOpens']) ? $data['trackOpens'] : null;
        $this->trackClicks = isset($data['trackClicks']) ? $data['trackClicks'] : null;
        $this->scheduleFor = isset($data['scheduleFor']) ? $data['scheduleFor'] : null;
        $this->splitOptions = isset($data['splitOptions']) ? $data['splitOptions'] : null;
    }

    /**
     * Gets deliveryOptimization.
     *
     * @return DeliveryOptimizationType|null
     */
    public function getDeliveryOptimization()
    {
        return $this->deliveryOptimization;
    }

    /**
     * Sets deliveryOptimization.
     *
     * @param DeliveryOptimizationType|null $deliveryOptimization  How to order email delivery - by recipients' engagement score or by the time they open the most of the emails that were sent to them
     *
     * @return $this
     */
    public function setDeliveryOptimization($deliveryOptimization = null)
    {
        $this->deliveryOptimization = $deliveryOptimization;

        return $this;
    }

    /**
     * Gets trackOpens.
     *
     * @return bool|null
     */
    public function isTrackOpens()
    {
        return $this->trackOpens;
    }

    /**
     * Sets trackOpens.
     *
     * @param bool|null $trackOpens  Should the opens be tracked? If no value has been provided, Account's default setting will be used.
     *
     * @return $this
     */
    public function setTrackOpens($trackOpens = null)
    {
        $this->trackOpens = $trackOpens;

        return $this;
    }

    /**
     * Gets trackClicks.
     *
     * @return bool|null
     */
    public function isTrackClicks()
    {
        return $this->trackClicks;
    }

    /**
     * Sets trackClicks.
     *
     * @param bool|null $trackClicks  Should the clicks be tracked? If no value has been provided, Account's default setting will be used.
     *
     * @return $this
     */
    public function setTrackClicks($trackClicks = null)
    {
        $this->trackClicks = $trackClicks;

        return $this;
    }

    /**
     * Gets scheduleFor.
     *
     * @return \DateTime|null
     */
    public function getScheduleFor(): ?\DateTime
    {
        return $this->scheduleFor;
    }

    /**
     * Sets scheduleFor.
     *
     * @param \DateTime|null $scheduleFor  Date when this Campaign is scheduled to be sent on
     *
     * @return $this
     */
    public function setScheduleFor(\DateTime $scheduleFor = null)
    {
        $this->scheduleFor = $scheduleFor;

        return $this;
    }

    /**
     * Gets splitOptions.
     *
     * @return SplitOptions|null
     */
    public function getSplitOptions()
    {
        return $this->splitOptions;
    }

    /**
     * Sets splitOptions.
     *
     * @param SplitOptions|null $splitOptions  Optional options for A/X split campaigns. Will be ignored if only one template content was provided
     *
     * @return $this
     */
    public function setSplitOptions($splitOptions = null)
    {
        $this->splitOptions = $splitOptions;

        return $this;
    }
}


