<?php
/**
 * ListsApiInterface
 * PHP version 7.1.3
 *
 * @category Class
 * @package  ElasticEmail
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Elastic Email REST API
 *
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://elasticemail.com/account#/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace ElasticEmail\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use ElasticEmail\Model\ContactsList;
use ElasticEmail\Model\EmailsPayload;
use ElasticEmail\Model\ListPayload;
use ElasticEmail\Model\ListUpdatePayload;

/**
 * ListsApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  ElasticEmail\Api
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
interface ListsApiInterface
{

    /**
     * Sets authentication method apikey
     *
     * @param string $value Value of the apikey authentication method.
     *
     * @return void
     */
    public function setapikey($value);

    /**
     * Operation listsByNameContactsPost
     *
     * Add Contacts to List
     *
     * @param  \string $name  Name of your list. (required)
     * @param  \ElasticEmail\Model\EmailsPayload $emailsPayload  Provide either rule or a list of emails, not both. (required)
     * @param  \int $responseCode     The HTTP response code to return
     * @param  \array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return \ElasticEmail\Model\ContactsList
     */
    public function listsByNameContactsPost($name, EmailsPayload $emailsPayload, &$responseCode, array &$responseHeaders);

    /**
     * Operation listsByNameContactsRemovePost
     *
     * Remove Contacts from List
     *
     * @param  \string $name  Name of your list. (required)
     * @param  \ElasticEmail\Model\EmailsPayload $emailsPayload  Provide either rule or a list of emails, not both. (required)
     * @param  \int $responseCode     The HTTP response code to return
     * @param  \array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     */
    public function listsByNameContactsRemovePost($name, EmailsPayload $emailsPayload, &$responseCode, array &$responseHeaders);

    /**
     * Operation listsByNameDelete
     *
     * Delete List
     *
     * @param  \string $name  Name of your list. (required)
     * @param  \int $responseCode     The HTTP response code to return
     * @param  \array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     */
    public function listsByNameDelete($name, &$responseCode, array &$responseHeaders);

    /**
     * Operation listsByNameGet
     *
     * Load List
     *
     * @param  \string $name  Name of your list. (required)
     * @param  \int $responseCode     The HTTP response code to return
     * @param  \array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return \ElasticEmail\Model\ContactsList
     */
    public function listsByNameGet($name, &$responseCode, array &$responseHeaders);

    /**
     * Operation listsByNamePut
     *
     * Update List
     *
     * @param  \string $name  Name of your list. (required)
     * @param  \ElasticEmail\Model\ListUpdatePayload $listUpdatePayload   (required)
     * @param  \int $responseCode     The HTTP response code to return
     * @param  \array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return \ElasticEmail\Model\ContactsList
     */
    public function listsByNamePut($name, ListUpdatePayload $listUpdatePayload, &$responseCode, array &$responseHeaders);

    /**
     * Operation listsGet
     *
     * Load Lists
     *
     * @param  \int $limit  Maximum number of returned items. (optional)
     * @param  \int $offset  How many items should be returned ahead. (optional)
     * @param  \int $responseCode     The HTTP response code to return
     * @param  \array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return \ElasticEmail\Model\ContactsList[]
     */
    public function listsGet($limit = null, $offset = null, &$responseCode, array &$responseHeaders);

    /**
     * Operation listsPost
     *
     * Add List
     *
     * @param  \ElasticEmail\Model\ListPayload $listPayload   (required)
     * @param  \int $responseCode     The HTTP response code to return
     * @param  \array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return \ElasticEmail\Model\ContactsList
     */
    public function listsPost(ListPayload $listPayload, &$responseCode, array &$responseHeaders);
}
