<?php
/**
 * VerificationsApiInterface
 * PHP version 7.1.3
 *
 * @category Class
 * @package  ElasticEmail
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Elastic Email REST API
 *
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://elasticemail.com/account#/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    This is the documentation for REST API. If you’d like to read our legacy documentation regarding Web API v2 click <a target=\"_blank\" href=\"https://api.elasticemail.com/public/help\">here</a>.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace ElasticEmail\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use ElasticEmail\Model\EmailValidationResult;
use ElasticEmail\Model\VerificationFileResult;
use ElasticEmail\Model\VerificationFileResultDetails;

/**
 * VerificationsApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  ElasticEmail\Api
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
interface VerificationsApiInterface
{

    /**
     * Sets authentication method apikey
     *
     * @param string $value Value of the apikey authentication method.
     *
     * @return void
     */
    public function setapikey($value);

    /**
     * Operation verificationsByEmailDelete
     *
     * Delete Email Verification Result
     *
     * @param  string $email  Email address to verification (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     *
     */
    public function verificationsByEmailDelete($email, &$responseCode, array &$responseHeaders);

    /**
     * Operation verificationsByEmailGet
     *
     * Get Email Verification Result
     *
     * @param  string $email  Email address to view verification result of (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return ElasticEmail\Model\EmailValidationResult
     *
     */
    public function verificationsByEmailGet($email, &$responseCode, array &$responseHeaders);

    /**
     * Operation verificationsByEmailPost
     *
     * Verify Email
     *
     * @param  string $email  Email address to verify (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return ElasticEmail\Model\EmailValidationResult
     *
     */
    public function verificationsByEmailPost($email, &$responseCode, array &$responseHeaders);

    /**
     * Operation verificationsFilesByIdDelete
     *
     * Delete File Verification Result
     *
     * @param  string $id  ID of the exported file (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     *
     */
    public function verificationsFilesByIdDelete($id, &$responseCode, array &$responseHeaders);

    /**
     * Operation verificationsFilesByIdResultDownloadGet
     *
     * Download File Verification Result
     *
     * @param  string $id  Verification ID to download (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return UploadedFile
     *
     */
    public function verificationsFilesByIdResultDownloadGet($id, &$responseCode, array &$responseHeaders);

    /**
     * Operation verificationsFilesByIdResultGet
     *
     * Get Detailed File Verification Result
     *
     * @param  string $id  ID of the Verification to display status of (required)
     * @param  int $limit  Maximum number of returned email verification results (optional)
     * @param  int $offset  How many result items should be returned ahead (optional)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return ElasticEmail\Model\VerificationFileResultDetails
     *
     */
    public function verificationsFilesByIdResultGet($id, $limit = null, $offset = null, &$responseCode, array &$responseHeaders);

    /**
     * Operation verificationsFilesPost
     *
     * Verify From File
     *
     * @param  UploadedFile $file   (optional)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return ElasticEmail\Model\VerificationFileResult
     *
     */
    public function verificationsFilesPost(UploadedFile $file = null, &$responseCode, array &$responseHeaders);

    /**
     * Operation verificationsFilesResultGet
     *
     * Get Simple Files Verification Results
     *
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return ElasticEmail\Model\VerificationFileResult[]
     *
     */
    public function verificationsFilesResultGet(&$responseCode, array &$responseHeaders);

    /**
     * Operation verificationsGet
     *
     * Get Emails Verification Results
     *
     * @param  int $limit  Maximum number of returned items. (optional)
     * @param  int $offset  How many items should be returned ahead. (optional)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return ElasticEmail\Model\EmailValidationResult[]
     *
     */
    public function verificationsGet($limit = null, $offset = null, &$responseCode, array &$responseHeaders);
}
